import React, { useEffect, useMemo, useState } from 'react';
import { Proposal, Contract } from '../types';
import { getStatusLabel, getStatusVariant, normalizeStatus } from '../constants/status';
import { Search, Eye, ArrowLeft, FileSignature, Check, X } from 'lucide-react';

interface Props {
  proposals: Proposal[];
  contracts: Contract[];
  loading?: boolean;
  error?: string | null;
  initialTab?: 'proposals' | 'contracts';
  selectedProposalId?: string | null;
  selectedContractId?: string | null;
  onSelectProposal: (id: string | null) => void;
  onSelectContract: (id: string | null) => void;
  onRefresh: () => void;
  onCompanyDecision: (id: string, status: 'ACCEPTED' | 'REJECTED') => Promise<void>;
  onOwnerDecision: (id: string, index: number, status: 'ACCEPTED' | 'REJECTED') => Promise<void>;
  onCreateContract: (proposalId: string, payload: any) => Promise<Contract | void>;
  onContractStatus: (id: string, status: string) => Promise<void>;
}

const Badge = ({ status }: { status?: string }) => <span className={`px-2 py-0.5 rounded text-[10px] font-bold font-mono ${getStatusVariant(status) === 'success' ? 'bg-emerald-100 text-emerald-800' : getStatusVariant(status) === 'warning' ? 'bg-amber-100 text-amber-800' : getStatusVariant(status) === 'danger' ? 'bg-rose-100 text-rose-800' : 'bg-slate-100 text-slate-700'}`}>{getStatusLabel(status)}</span>;
const money = (amount?: number, currency = 'XOF') => new Intl.NumberFormat('fr-FR', { style: 'currency', currency, maximumFractionDigits: 0 }).format(Number(amount || 0));
const date = (value?: string) => value ? value.slice(0, 10) : '—';

export const CommercialView: React.FC<Props> = ({ proposals, contracts, loading, error, initialTab = 'proposals', selectedProposalId, selectedContractId, onSelectProposal, onSelectContract, onRefresh, onCompanyDecision, onOwnerDecision, onCreateContract, onContractStatus }) => {
  const [activeTab, setActiveTab] = useState<'proposals' | 'contracts'>(initialTab);
  const [search, setSearch] = useState('');
  const [actionError, setActionError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [form, setForm] = useState({ title: 'Contrat lié à la proposition', startDate: '', endDate: '', amount: '', currency: 'XOF', paymentTerms: '', conditions: '', responsibilities: '' });

  useEffect(() => setActiveTab(initialTab), [initialTab]);
  const selectedProposal = proposals.find((p) => p.id === selectedProposalId) || null;
  const selectedContract = contracts.find((c) => c.id === selectedContractId) || null;
  useEffect(() => {
    if (selectedProposal) setForm((f) => ({ ...f, amount: String(selectedProposal.finalPrice || selectedProposal.totalEstimated || 0), currency: selectedProposal.currency || 'XOF' }));
  }, [selectedProposal]);

  const filteredProposals = useMemo(() => proposals.filter((p) => [p.title, p.requestTitle, p.companyName, p.workflowStatus, p.status].join(' ').toLowerCase().includes(search.toLowerCase())), [proposals, search]);
  const filteredContracts = useMemo(() => contracts.filter((c) => [c.contractNumber, c.title, c.companyName, c.status].join(' ').toLowerCase().includes(search.toLowerCase())), [contracts, search]);

  const run = async (fn: () => Promise<any>, ok: string) => { setActionError(null); setSuccess(null); try { const result = await fn(); setSuccess(ok); onRefresh(); return result; } catch (e: any) { setActionError(e?.message || 'Action impossible depuis DEL-api.'); } };

  if (selectedProposal) {
    const ready = normalizeStatus(selectedProposal.workflowStatus) === 'READY_FOR_CONTRACT' || normalizeStatus(selectedProposal.status) === 'ACCEPTED';
    return <div className="space-y-5">
      <button onClick={() => onSelectProposal(null)} className="text-xs font-bold text-slate-600 hover:text-slate-950 flex items-center gap-1"><ArrowLeft size={14}/>Retour aux propositions</button>
      {(actionError || success) && <div className={`rounded border p-3 text-xs font-semibold ${actionError ? 'bg-rose-50 border-rose-200 text-rose-800' : 'bg-emerald-50 border-emerald-200 text-emerald-800'}`}>{actionError || success}</div>}
      <section className="bg-white border border-slate-200 rounded-xl p-5 shadow-xs space-y-4">
        <div className="flex justify-between gap-3 flex-wrap"><div><h2 className="font-black text-slate-950">{selectedProposal.title || selectedProposal.requestTitle}</h2><p className="text-xs text-slate-500 font-mono">{selectedProposal.code}</p></div><div className="flex gap-2"><Badge status={selectedProposal.status}/><Badge status={selectedProposal.workflowStatus}/></div></div>
        <div className="grid md:grid-cols-4 gap-3 text-xs"><Info label="Entreprise" value={selectedProposal.companyName}/><Info label="Montant" value={money(selectedProposal.finalPrice || selectedProposal.totalEstimated, selectedProposal.currency)}/><Info label="Durée" value={`${selectedProposal.durationMonths || 0} mois`}/><Info label="Créée le" value={date(selectedProposal.createdAt)}/></div>
      </section>
      <Grid title="Demande / appel d’offres lié" items={[['requestId', selectedProposal.requestId], ['tenderId', selectedProposal.tenderId], ['tenderLotId', selectedProposal.tenderLotId]]}/>
      <Grid title="Engins proposés" items={(selectedProposal.equipmentIds || []).map((id, i) => [`Engin ${i + 1}`, id])}/>
      <section className="bg-white border border-slate-200 rounded-xl p-5 space-y-3"><h3 className="font-bold text-sm">Décision entreprise</h3><Decision d={selectedProposal.companyDecision}/><div className="flex gap-2"><button onClick={() => run(() => onCompanyDecision(selectedProposal.id, 'ACCEPTED'), 'Décision entreprise acceptée.')} className="bg-emerald-500 text-white rounded px-3 py-1.5 text-xs font-bold flex items-center gap-1"><Check size={12}/>Accepter entreprise</button><button onClick={() => run(() => onCompanyDecision(selectedProposal.id, 'REJECTED'), 'Décision entreprise refusée.')} className="bg-rose-500 text-white rounded px-3 py-1.5 text-xs font-bold flex items-center gap-1"><X size={12}/>Refuser entreprise</button></div></section>
      <section className="bg-white border border-slate-200 rounded-xl p-5 space-y-3"><h3 className="font-bold text-sm">Décisions propriétaires</h3>{(selectedProposal.ownerDecisions || []).length ? selectedProposal.ownerDecisions?.map((d, i) => <div key={i} className="border rounded-lg p-3 space-y-2"><Decision d={{ ownerName: selectedProposal.ownerNames?.[i], ...d }}/><div className="flex gap-2"><button onClick={() => run(() => onOwnerDecision(selectedProposal.id, i, 'ACCEPTED'), 'Décision propriétaire acceptée.')} className="bg-emerald-500 text-white rounded px-3 py-1.5 text-xs font-bold flex items-center gap-1">Accepter</button><button onClick={() => run(() => onOwnerDecision(selectedProposal.id, i, 'REJECTED'), 'Décision propriétaire refusée.')} className="bg-rose-500 text-white rounded px-3 py-1.5 text-xs font-bold flex items-center gap-1">Refuser</button></div></div>) : <p className="text-xs text-slate-500">Aucune décision propriétaire reçue.</p>}</section>
      <section className="bg-white border border-slate-200 rounded-xl p-5 space-y-3"><h3 className="font-bold text-sm flex gap-2"><FileSignature size={16}/>Créer contrat</h3>{!ready && <p className="text-xs bg-amber-50 border border-amber-200 text-amber-800 rounded p-3">Le contrat pourra être créé après acceptation de l’entreprise et des propriétaires.</p>}{ready && <div className="grid md:grid-cols-2 gap-3">{(['title','startDate','endDate','amount','currency','paymentTerms','conditions','responsibilities'] as const).map(k => <input key={k} type={k.includes('Date') ? 'date' : 'text'} value={form[k]} onChange={e => setForm({...form, [k]: e.target.value})} placeholder={k} className="border rounded px-3 py-2 text-xs" />)}<button className="md:col-span-2 bg-amber-500 text-slate-950 font-black rounded px-4 py-2 text-xs" onClick={() => run(async () => { const c = await onCreateContract(selectedProposal.id, { ...form, amount: Number(form.amount) }); if (c?.id) onSelectContract(c.id); }, 'Contrat créé depuis la proposition.')}>Créer le contrat</button></div>}</section>
    </div>;
  }

  if (selectedContract) return <div className="space-y-5"><button onClick={() => onSelectContract(null)} className="text-xs font-bold text-slate-600 hover:text-slate-950 flex items-center gap-1"><ArrowLeft size={14}/>Retour aux contrats</button>{(actionError || success) && <div className={`rounded border p-3 text-xs font-semibold ${actionError ? 'bg-rose-50 border-rose-200 text-rose-800' : 'bg-emerald-50 border-emerald-200 text-emerald-800'}`}>{actionError || success}</div>}<section className="bg-white border rounded-xl p-5 space-y-4"><div className="flex justify-between"><div><h2 className="font-black">{selectedContract.title}</h2><p className="text-xs font-mono text-slate-500">{selectedContract.contractNumber}</p></div><Badge status={selectedContract.status}/></div><div className="grid md:grid-cols-3 gap-3 text-xs"><Info label="Entreprise" value={selectedContract.companyName}/><Info label="Propriétaires" value={(selectedContract.ownerNames || []).join(', ') || '—'}/><Info label="Engins" value={(selectedContract.equipmentIds || []).join(', ') || selectedContract.engineName}/><Info label="Montant" value={money(selectedContract.amount || selectedContract.totalAmount, selectedContract.currency)}/><Info label="Commission" value={`${selectedContract.platformCommissionRate || 0}% · ${money(selectedContract.platformCommissionAmount, selectedContract.currency)}`}/><Info label="Part propriétaires" value={money(selectedContract.ownerAmount, selectedContract.currency)}/><Info label="Début" value={date(selectedContract.startDate)}/><Info label="Fin" value={date(selectedContract.endDate)}/><Info label="Paiement" value={selectedContract.paymentTerms || '—'}/></div><Grid title="Conditions" items={[['conditions', selectedContract.conditions], ['responsabilités', selectedContract.responsibilities]]}/><div className="flex flex-wrap gap-2">{['PENDING_SIGNATURE','ACTIVE','COMPLETED','CANCELLED'].map(s => <button key={s} onClick={() => run(() => onContractStatus(selectedContract.id, s), `Statut contrat changé en ${getStatusLabel(s)}.`)} className="bg-slate-900 text-white rounded px-3 py-1.5 text-xs font-bold">{getStatusLabel(s)}</button>)}</div><p className="text-xs text-slate-500 border-t pt-3">Les factures seront connectées dans l’itération suivante.</p></section></div>;

  return <div className="space-y-5"><div className="flex flex-col sm:flex-row justify-between gap-3 bg-slate-900 text-white p-4 rounded-lg"><div className="flex gap-2"><button onClick={() => setActiveTab('proposals')} className={`px-4 py-2 rounded text-xs font-black ${activeTab === 'proposals' ? 'bg-amber-500 text-slate-950' : 'bg-slate-800'}`}>Propositions ({proposals.length})</button><button onClick={() => setActiveTab('contracts')} className={`px-4 py-2 rounded text-xs font-black ${activeTab === 'contracts' ? 'bg-amber-500 text-slate-950' : 'bg-slate-800'}`}>Contrats ({contracts.length})</button></div><label className="relative"><Search size={13} className="absolute left-3 top-2.5 text-slate-500"/><input value={search} onChange={e => setSearch(e.target.value)} className="bg-slate-950 border border-slate-700 rounded py-2 pl-8 pr-3 text-xs" placeholder="Filtrer..."/></label></div>{loading && <p className="text-xs text-slate-500">Chargement DEL-api…</p>}{error && <p className="bg-rose-50 border border-rose-200 text-rose-800 p-3 rounded text-xs font-semibold">{error}</p>}{activeTab === 'proposals' ? <Table empty="Aucune proposition pour le moment." rows={filteredProposals.map(p => [p.title || p.requestTitle, p.companyName, (p.ownerNames || []).join(', ') || '—', money(p.finalPrice || p.totalEstimated, p.currency), <Badge status={p.status}/>, <Badge status={p.workflowStatus}/>, date(p.createdAt), <button onClick={() => onSelectProposal(p.id)} className="text-indigo-700 font-bold flex items-center gap-1"><Eye size={13}/>Voir détail</button>])} headers={['Titre','Entreprise','Propriétaires','Montant','Statut','Workflow','Création','Action']}/> : <Table empty="Aucun contrat pour le moment." rows={filteredContracts.map(c => [c.contractNumber || c.code, c.title || 'Contrat DEL', c.companyName, (c.ownerNames || []).join(', ') || '—', money(c.amount || c.totalAmount, c.currency), <Badge status={c.status}/>, date(c.startDate), date(c.endDate), <button onClick={() => onSelectContract(c.id)} className="text-indigo-700 font-bold flex items-center gap-1"><Eye size={13}/>Voir détail</button>])} headers={['Numéro','Titre','Entreprise','Propriétaires','Montant','Statut','Début','Fin','Action']}/>}</div>;
};

function Info({ label, value }: { label: string; value: any; key?: any }) { return <div><span className="text-slate-400 block text-[10px] uppercase">{label}</span><span className="font-semibold text-slate-800 font-mono">{value || '—'}</span></div>; }
function Decision({ d }: { d: any }) { return <div className="grid md:grid-cols-4 gap-3 text-xs"><Info label="Nom" value={d?.ownerName}/><Info label="Statut" value={<Badge status={d?.status}/>}/><Info label="Date" value={date(d?.decidedAt)}/><Info label="Notes / rejet" value={d?.notes || d?.rejectionReason || '—'}/></div>; }
function Grid({ title, items }: { title: string; items: any[] }) { return <section className="bg-white border border-slate-200 rounded-xl p-5"><h3 className="font-bold text-sm mb-3">{title}</h3><div className="grid md:grid-cols-3 gap-3 text-xs">{items.length ? items.map(([l, v], i) => <Info key={i} label={l} value={v}/>) : <p className="text-slate-500">Aucune donnée.</p>}</div></section>; }
function Table({ headers, rows, empty }: { headers: string[]; rows: any[][]; empty: string }) { return <div className="bg-white border rounded-xl overflow-x-auto"><table className="w-full text-xs"><thead className="bg-slate-50 text-slate-500"><tr>{headers.map(h => <th key={h} className="text-left p-3 font-bold">{h}</th>)}</tr></thead><tbody>{rows.length ? rows.map((r, i) => <tr key={i} className="border-t">{r.map((c, j) => <td key={j} className="p-3 align-top">{c}</td>)}</tr>) : <tr><td colSpan={headers.length} className="p-8 text-center text-slate-500">{empty}</td></tr>}</tbody></table></div>; }
