'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {getAuditLogs} from '../../lib/api';

const modules=['','AUTH','USER','OWNER','COMPANY','TECHNICIAN','EQUIPMENT','REQUEST','TENDER','TENDER_LOT','TENDER_SUBMISSION','PROPOSAL','CONTRACT','INVOICE','PAYMENT','DOCUMENT','MISSION','MISSION_REPORT','MAINTENANCE','PLANNING','SCORING','REPORT','SETTINGS','NOTIFICATION','MESSAGE','SYSTEM'];
const actions=['','CREATE','UPDATE','DELETE','STATUS_CHANGE','LOGIN','LOGOUT','REGISTER','APPROVE','REJECT','DOWNLOAD','EXPORT','PAYMENT_RECORD','MESSAGE_SENT','NOTIFICATION_SENT','SETTINGS_UPDATE','SYSTEM'];
const severities=['','LOW','NORMAL','HIGH','CRITICAL'];
const badge=(value,type='neutral')=>`rounded-full px-2 py-1 text-xs font-bold ${type==='severity'&&value==='CRITICAL'?'bg-red-100 text-red-700':type==='severity'&&value==='HIGH'?'bg-yellow-100 text-yellow-700':type==='severity'&&value==='LOW'?'bg-gray-100 text-gray-700':'bg-blue-50 text-blue-700'}`;
const formatDate=(d)=>d?new Date(d).toLocaleString('fr-FR'):'—';

export default function AuditPage(){const [filters,setFilters]=useState({limit:100}),[logs,setLogs]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');const load=()=>{setLoading(true);setError('');getAuditLogs(filters).then(setLogs).catch(e=>setError(e.message)).finally(()=>setLoading(false));};useEffect(load,[]);const fields=useMemo(()=>[{k:'module',opts:modules},{k:'action',opts:actions},{k:'actorRole'},{k:'entityType'},{k:'severity',opts:severities},{k:'dateFrom',type:'date'},{k:'dateTo',type:'date'}],[]);return <section><div className="flex items-center justify-between gap-4"><div><h1 className="text-4xl font-black">Audit log</h1><p className="mt-2 text-sm text-gray-600">Historique des 100 dernières actions et filtres simples.</p></div><button onClick={load} className="rounded bg-forest px-4 py-2 font-bold text-white">Actualiser</button></div><div className="panel mt-6 grid gap-3 md:grid-cols-4">{fields.map(f=><label key={f.k} className="text-sm font-bold uppercase text-gray-500">{f.k}{f.opts?<select className="mt-1 w-full rounded border p-2 normal-case" value={filters[f.k]||''} onChange={e=>setFilters({...filters,[f.k]:e.target.value})}>{f.opts.map(o=><option key={o} value={o}>{o||'Tous'}</option>)}</select>:<input type={f.type||'text'} className="mt-1 w-full rounded border p-2 normal-case" value={filters[f.k]||''} onChange={e=>setFilters({...filters,[f.k]:e.target.value})}/>}</label>)}<button onClick={load} className="rounded bg-gold px-4 py-2 font-bold text-coal md:mt-6">Filtrer</button></div>{loading&&<p className="panel mt-6">Chargement...</p>}{error&&<p className="alert-error mt-6">{error}</p>}{!loading&&!error&&logs.length===0&&<p className="panel mt-6">Aucun audit trouvé.</p>}{!loading&&!error&&logs.length>0&&<div className="panel mt-6 overflow-x-auto"><table className="min-w-[1100px] w-full text-left text-sm"><thead><tr className="border-b text-xs uppercase text-gray-500"><th>Date</th><th>Acteur</th><th>Rôle</th><th>Action</th><th>Module</th><th>Entité</th><th>Label</th><th>Message</th><th>Sévérité</th><th>Actions</th></tr></thead><tbody>{logs.map(l=><tr key={l._id} className="border-b last:border-0"><td className="py-3">{formatDate(l.createdAt)}</td><td>{l.actorName||'Système'}</td><td>{l.actorRole||'—'}</td><td><span className={badge(l.action)}>{l.action}</span></td><td><span className={badge(l.module)}>{l.module}</span></td><td>{l.entityType}<br/><span className="text-xs text-gray-500">{l.entityId}</span></td><td>{l.entityLabel||'—'}</td><td>{l.message||'—'}</td><td><span className={badge(l.severity,'severity')}>{l.severity}</span></td><td><Link className="font-bold text-forest" href={`/audit/${l._id}`}>Voir détail</Link></td></tr>)}</tbody></table></div>}</section>}
