'use client';
import {useEffect,useState} from 'react';import {getAdminSettings,resetSettingsToDefault,updateAdminSettings} from '../../lib/api';
const identity=['platformName','legalName','slogan','description','logoUrl','faviconUrl','primaryColor','secondaryColor','accentColor'];
const contact=['email','phone','whatsapp','website','address','country','city'];const legal=['rccm','ifu','taxNumber','registrationNumber'];
const finance=['defaultCurrency','enabledCurrencies','defaultPlatformCommissionRate','defaultTaxRate','invoicePrefix','contractPrefix','paymentPrefix'];
const options=['allowPublicEquipmentSubmission','allowPublicRequestSubmission','requireAdminApprovalForEquipment','requireAdminApprovalForRequests','requireDocumentsForVerification','enableTenderModule','enableTenderSubmissions','enableScoring','enablePdfReports','enableInternalMessaging','enableNotifications'];
const legalTexts=['termsOfService','privacyPolicy','rentalTerms','ownerTerms','companyTerms','investmentDisclaimer','paymentTerms','contractLegalNotice','invoiceLegalNotice'];
const publicTexts=['homepageHeroTitle','homepageHeroSubtitle','homepageCtaText','equipmentSubmissionNotice','requestSubmissionNotice','tenderSubmissionNotice'];
function Card({title,children}){return <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-xl font-black">{title}</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{children}</div></section>}
export default function SettingsPage(){const [form,setForm]=useState({}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[msg,setMsg]=useState('');useEffect(()=>{getAdminSettings().then(setForm).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);const set=(k,v)=>setForm(f=>({...f,[k]:v}));async function save(){setError('');setMsg('');try{const payload={...form,enabledCurrencies:String(form.enabledCurrencies||'').split(',').map(x=>x.trim()).filter(Boolean)};const saved=await updateAdminSettings(payload);setForm(saved);setMsg('Paramètres sauvegardés.')}catch(e){setError(e.message)}}async function reset(){if(!confirm('Réinitialiser les paramètres par défaut ?'))return;const saved=await resetSettingsToDefault();setForm(saved);setMsg('Paramètres réinitialisés.')}function input(k){if(k==='enabledCurrencies')return <input key={k} className="input" value={(form[k]||[]).join ? form[k].join(', ') : form[k]||''} onChange={e=>set(k,e.target.value)} placeholder="XOF, USD, EUR"/>;if(k==='defaultCurrency')return <select key={k} className="input" value={form[k]||'XOF'} onChange={e=>set(k,e.target.value)}>{['XOF','USD','EUR'].map(c=><option key={c}>{c}</option>)}</select>;return <input key={k} className="input" type={k.includes('Rate')?'number':'text'} value={form[k]??''} onChange={e=>set(k,e.target.value)} placeholder={k}/>}
if(loading)return <p className="panel">Chargement des paramètres...</p>;return <section className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-4xl font-black">Paramètres plateforme</h1><p className="text-gray-600">Informations DEL, commissions, devises, textes légaux et options métier.</p></div><div className="flex gap-2"><button className="btn bg-gold text-coal" onClick={save}>Sauvegarder</button><button className="btn bg-red-100 text-red-800" onClick={reset}>Réinitialiser par défaut</button></div></div>{msg&&<p className="alert-success">{msg}</p>}{error&&<p className="alert-error">{error}</p>}<Card title="Identité DEL">{identity.map(k=><label key={k} className="grid gap-1 text-sm font-bold">{k}{input(k)}</label>)}</Card><Card title="Coordonnées">{contact.map(k=><label key={k} className="grid gap-1 text-sm font-bold">{k}{input(k)}</label>)}</Card><Card title="Informations légales">{legal.map(k=><label key={k} className="grid gap-1 text-sm font-bold">{k}{input(k)}</label>)}</Card><Card title="Paramètres financiers">{finance.map(k=><label key={k} className="grid gap-1 text-sm font-bold">{k}{input(k)}</label>)}</Card><Card title="Options métier">{options.map(k=><label key={k} className="flex items-center justify-between rounded-xl border p-3"><span>{k}</span><span className={form[k]?'badge bg-green-100 text-green-800':'badge bg-red-100 text-red-800'}>{form[k]?'Activé':'Désactivé'}</span><input type="checkbox" checked={!!form[k]} onChange={e=>set(k,e.target.checked)}/></label>)}</Card><Card title="Textes légaux">{legalTexts.map(k=><label key={k} className="grid gap-1 text-sm font-bold md:col-span-2">{k}<textarea className="input min-h-28" value={form[k]||''} onChange={e=>set(k,e.target.value)}/></label>)}</Card><Card title="Textes publics">{publicTexts.map(k=><label key={k} className="grid gap-1 text-sm font-bold md:col-span-2">{k}<textarea className="input" value={form[k]||''} onChange={e=>set(k,e.target.value)}/></label>)}</Card><div className="flex gap-2"><button className="btn bg-gold text-coal" onClick={save}>Sauvegarder</button><button className="btn bg-red-100 text-red-800" onClick={reset}>Réinitialiser par défaut</button></div></section>}
